import type { HeroSlideRow } from "@/lib/validation/hero";

/**
 * Local-engine seed for hero_slides.
 *
 * DRAFT COPY — every string here is editable in /admin/hero and only
 * claims the brand has already approved. The Supabase cutover seed that
 * mirrors these rows lives in supabase/seed/hero_slides.sql.
 *
 * Sort grows in tens so admin reordering can slot rows between neighbours.
 */
export type HeroSlideSeed = Omit<HeroSlideRow, "id" | "sort" | "updatedAt"> & { key: string };

export const heroSeed: HeroSlideSeed[] = [
  {
    key: "tide-slide-midnight",
    isActive: true,
    productId: "p_tide_slide",
    colorwayId: "cw_tide_slide_midnight",
    eyebrow: "Monsoon '26",
    headlineBefore: "Light on land.",
    headlineItalic: "At home",
    headlineAfter: " in water.",
    lead: "A cushioned EVA sole, a quiet strap, and a grip that stays honest in the rain. Comfort, waterproofing, and almost no weight — the claims we are allowed to make, and the ones the sole has to keep.",
    glowHex: "#1E7F78",
    imageDesktopPath: "/catalog/hero-tide-slide.jpg",
    imageMobilePath: "/catalog/hero/tide-slide/hero-mobile",
    imageAlt: "Aqualite Tide Slide in midnight with an aqua accent on a warm ivory stage",
    focalX: 0.58,
    focalY: 0.42,
    shoeMaskPath: null,
    ctaPrimaryLabel: "Shop Tide",
    ctaPrimaryHref: "/product/tide-slide?color=midnight",
    ctaSecondaryLabel: "All slides",
    ctaSecondaryHref: "/collections/everyday-slides",
    startsAt: null,
    endsAt: null,
  },
  {
    key: "pearl-slide-blush",
    isActive: true,
    productId: "p_pearl_slide",
    colorwayId: "cw_pearl_slide_blush",
    eyebrow: "Monsoon '26",
    headlineBefore: "Soft underfoot.",
    headlineItalic: "Quiet",
    headlineAfter: " on the street.",
    lead: "A contoured footbed and a rounded strap that stays soft through a wet commute. Light enough to forget, finished enough to wear out.",
    glowHex: "#B9828C",
    imageDesktopPath: "/catalog/hero/pearl-slide/hero-desktop",
    imageMobilePath: "/catalog/hero/pearl-slide/hero-mobile",
    imageAlt: "Aqualite Pearl Slide in blush pink on a warm ivory stage",
    focalX: 0.5,
    focalY: 0.45,
    shoeMaskPath: null,
    ctaPrimaryLabel: "Shop Pearl",
    ctaPrimaryHref: "/product/pearl-slide?color=blush",
    ctaSecondaryLabel: "All slides",
    ctaSecondaryHref: "/collections/everyday-slides",
    startsAt: null,
    endsAt: null,
  },
  {
    key: "cove-clog-sage",
    isActive: true,
    productId: "p_cove_clog",
    colorwayId: "cw_cove_clog_sage",
    eyebrow: "Monsoon '26",
    headlineBefore: "Closed toe.",
    headlineItalic: "Open",
    headlineAfter: " to rain.",
    lead: "A one-piece EVA shell that drains, dries and keeps its shape. For puddles, gardens and every step in between.",
    glowHex: "#6F9A82",
    imageDesktopPath: "/catalog/hero/cove-clog/hero-desktop",
    imageMobilePath: "/catalog/hero/cove-clog/hero-mobile",
    imageAlt: "Aqualite Cove Clog in sage green on a warm ivory stage",
    focalX: 0.5,
    focalY: 0.45,
    shoeMaskPath: null,
    ctaPrimaryLabel: "Shop Cove",
    ctaPrimaryHref: "/product/cove-clog?color=sage",
    ctaSecondaryLabel: "All clogs",
    ctaSecondaryHref: "/shop?category=clogs",
    startsAt: null,
    endsAt: null,
  },
  {
    key: "harbour-clog-navy",
    isActive: true,
    productId: "p_harbour_clog",
    colorwayId: "cw_harbour_clog_navy",
    eyebrow: "Monsoon '26",
    headlineBefore: "Made for puddles.",
    headlineItalic: "Worn",
    headlineAfter: " long after.",
    lead: "A deeper heel cup and a grip that holds wet stone. The clog you stop taking off at the door.",
    glowHex: "#2E4F7F",
    imageDesktopPath: "/catalog/hero/harbour-clog/hero-desktop",
    imageMobilePath: "/catalog/hero/harbour-clog/hero-mobile",
    imageAlt: "Aqualite Harbour Clog in navy on a warm ivory stage",
    focalX: 0.5,
    focalY: 0.45,
    shoeMaskPath: null,
    ctaPrimaryLabel: "Shop Harbour",
    ctaPrimaryHref: "/product/harbour-clog?color=navy",
    ctaSecondaryLabel: "All clogs",
    ctaSecondaryHref: "/shop?category=clogs",
    startsAt: null,
    endsAt: null,
  },
  {
    key: "reef-flip-porcelain",
    isActive: true,
    productId: "p_reef_flip",
    colorwayId: "cw_reef_flip_porcelain",
    eyebrow: "Monsoon '26",
    headlineBefore: "One strap.",
    headlineItalic: "Nothing",
    headlineAfter: " else.",
    lead: "The lightest pair we make. A soft toe post, a textured sole, and nothing you need to think about.",
    glowHex: "#BFA77E",
    imageDesktopPath: "/catalog/hero/reef-flip/hero-desktop",
    imageMobilePath: "/catalog/hero/reef-flip/hero-mobile",
    imageAlt: "Aqualite Reef Flip in porcelain white on a warm ivory stage",
    focalX: 0.5,
    focalY: 0.45,
    shoeMaskPath: null,
    ctaPrimaryLabel: "Shop Reef",
    ctaPrimaryHref: "/product/reef-flip?color=porcelain",
    ctaSecondaryLabel: "Shop men",
    ctaSecondaryHref: "/shop/men",
    startsAt: null,
    endsAt: null,
  },
];
