"use client";

import { useMemo, useState } from "react";

type Entry = { id: string; variantId: string; delta: number; reason: string; refOrderId: string | null; actor: string; note: string; at: string };
export function LedgerTable({ entries, skus }: { entries: Entry[]; skus: Record<string, string> }) {
  const [search, setSearch] = useState(""); const [reason, setReason] = useState("all"); const [page, setPage] = useState(0);
  const reasons = [...new Set(entries.map((entry) => entry.reason))];
  const filtered = useMemo(() => entries.filter((row) => (reason === "all" || row.reason === reason) && `${skus[row.variantId]} ${row.refOrderId ?? ""} ${row.actor}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.at.localeCompare(a.at)), [entries, skus, reason, search]);
  return <div><div className="mb-4 flex gap-3 text-small"><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} placeholder="SKU, order or actor" aria-label="Search stock ledger" className="hub-input" /><select value={reason} onChange={(event) => { setReason(event.target.value); setPage(0); }} className="hub-input"><option value="all">All reasons</option>{reasons.map((value) => <option key={value}>{value}</option>)}</select></div>
    <div className="max-h-[660px] overflow-auto border border-hairline bg-porcelain"><table className="w-full text-left text-small"><thead className="sticky top-0 bg-porcelain font-mono text-eyebrow uppercase text-mist"><tr><th className="p-3">Date · IST</th><th>SKU</th><th>Change</th><th>Reason</th><th>Actor</th><th>Order</th><th>Note</th></tr></thead><tbody>{filtered.slice(page * 100, page * 100 + 100).map((row) => <tr key={row.id} className="border-t border-hairline"><td className="p-3 font-mono">{new Date(row.at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</td><td className="font-mono">{skus[row.variantId] ?? row.variantId}</td><td className={row.delta < 0 ? "text-danger" : "text-success"}>{row.delta > 0 ? "+" : ""}{row.delta}</td><td>{row.reason}</td><td>{row.actor}</td><td className="font-mono">{row.refOrderId ?? "—"}</td><td>{row.note}</td></tr>)}</tbody></table>{!filtered.length && <p className="p-6 text-mist">No ledger entries match this filter.</p>}</div><div className="mt-3 flex gap-3 text-small"><button disabled={page === 0} onClick={() => setPage(page - 1)} className="text-aqua disabled:opacity-40">← Previous</button><span>Page {page + 1} / {Math.max(1, Math.ceil(filtered.length / 100))}</span><button disabled={(page + 1) * 100 >= filtered.length} onClick={() => setPage(page + 1)} className="text-aqua disabled:opacity-40">Next →</button></div></div>;
}
