/**
 * Hero image pipeline (H02).
 *
 * Reads public/catalog/hero/_src/<slug>-desktop.(jpg|png) and -mobile.(jpg|png),
 * emits per-slide AVIF + WebP ladders, a JPEG fallback, 24px blur placeholders,
 * samples the rendered glow colour, and writes:
 *   public/catalog/hero/manifest.json          (runtime, keyed by DB image path)
 *   lib/catalog/hero-manifest.ts               (typed module for the hero loader)
 *
 * Run: node --experimental-strip-types scripts/hero-images.ts
 * Re-run any time photography is re-delivered into _src/.
 */
import fs from "node:fs";
import path from "node:path";

import {
  DESKTOP_BUDGET_BYTES,
  DESKTOP_WIDTHS,
  MOBILE_BUDGET_BYTES,
  MOBILE_WIDTHS,
  OUT_ROOT,
  ROOT,
  blurPlaceholder,
  encodeLadder,
  sampleGlow,
  sourceOf,
} from "./hero-lib.ts";

/** DB image path → which source + ladder it resolves to. */
const SLIDES = [
  {
    slug: "tide-slide",
    quality: "render",
    desktopKey: "/catalog/hero-tide-slide.jpg",
    desktopBase: "/catalog/hero/tide-slide/hero-desktop",
    mobileKey: "/catalog/hero/tide-slide/hero-mobile",
    mobileBase: "/catalog/hero/tide-slide/hero-mobile",
  },
  {
    slug: "pearl-slide",
    quality: "render",
    desktopKey: "/catalog/hero/pearl-slide/hero-desktop",
    desktopBase: "/catalog/hero/pearl-slide/hero-desktop",
    mobileKey: "/catalog/hero/pearl-slide/hero-mobile",
    mobileBase: "/catalog/hero/pearl-slide/hero-mobile",
  },
  {
    slug: "cove-clog",
    quality: "render",
    desktopKey: "/catalog/hero/cove-clog/hero-desktop",
    desktopBase: "/catalog/hero/cove-clog/hero-desktop",
    mobileKey: "/catalog/hero/cove-clog/hero-mobile",
    mobileBase: "/catalog/hero/cove-clog/hero-mobile",
  },
  {
    slug: "harbour-clog",
    quality: "render",
    desktopKey: "/catalog/hero/harbour-clog/hero-desktop",
    desktopBase: "/catalog/hero/harbour-clog/hero-desktop",
    mobileKey: "/catalog/hero/harbour-clog/hero-mobile",
    mobileBase: "/catalog/hero/harbour-clog/hero-mobile",
  },
  {
    slug: "reef-flip",
    quality: "render",
    desktopKey: "/catalog/hero/reef-flip/hero-desktop",
    desktopBase: "/catalog/hero/reef-flip/hero-desktop",
    mobileKey: "/catalog/hero/reef-flip/hero-mobile",
    mobileBase: "/catalog/hero/reef-flip/hero-mobile",
  },
] as const;

const manifest: { generatedAt: string; entries: Record<string, unknown> } = {
  generatedAt: new Date().toISOString(),
  entries: {},
};

let failures = 0;

for (const slide of SLIDES) {
  const desktopSrc = await sourceOf("desktop", slide.slug);
  const mobileSrc = await sourceOf("mobile", slide.slug);
  if (!desktopSrc || !mobileSrc) {
    failures += 1;
    process.exitCode = 1;
    console.error(`[hero-images] missing source for ${slide.slug} (desktop: ${Boolean(desktopSrc)}, mobile: ${Boolean(mobileSrc)})`);
    continue;
  }
  const outDir = path.join(OUT_ROOT, slide.slug);
  const desktop = await encodeLadder(desktopSrc, outDir, "hero-desktop", DESKTOP_WIDTHS, 1920, DESKTOP_BUDGET_BYTES);
  const mobile = await encodeLadder(mobileSrc, outDir, "hero-mobile", MOBILE_WIDTHS, 828, MOBILE_BUDGET_BYTES);
  const glowHex = await sampleGlow(desktopSrc.path);
  const blurDesktop = await blurPlaceholder(desktopSrc);
  const blurMobile = await blurPlaceholder(mobileSrc);

  for (const [key, base, ladder, blur, aspect] of [
    [slide.desktopKey, slide.desktopBase, desktop, blurDesktop, desktopSrc.width / desktopSrc.height],
    [slide.mobileKey, slide.mobileBase, mobile, blurMobile, mobileSrc.width / mobileSrc.height],
  ] as const) {
    manifest.entries[key] = {
      base,
      quality: slide.quality,
      widths: ladder.widths,
      formats: ladder.formats,
      fallback: ladder.fallback ? `${base}-${ladder.fallback}` : null,
      blurDataURL: blur,
      aspect,
      glowHex,
      bytes: ladder.bytes,
      withinBudget: ladder.withinBudget,
    };
  }
  console.log(
    `[hero-images] ${slide.slug}: desktop ${desktop.widths.join("/")} avif-max=${Math.round((desktop.bytes[`avif:${desktop.widths.at(-1)}`] ?? 0) / 1024)}KB, mobile ${mobile.widths.join("/")} avif-828=${Math.round((mobile.bytes["avif:828"] ?? 0) / 1024)}KB, glow ${glowHex}`,
  );
}

fs.writeFileSync(path.join(OUT_ROOT, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

const ts = `/* Generated by scripts/hero-images.ts — do not edit by hand.
 * Regenerate: node --experimental-strip-types scripts/hero-images.ts */

export type HeroMediaEntry = {
  base: string;
  quality: "render" | "composite";
  widths: number[];
  formats: string[];
  fallback: string | null;
  blurDataURL: string;
  aspect: number;
  glowHex: string;
  withinBudget: boolean;
};

const RUNTIME_KEYS = ["base", "quality", "widths", "formats", "fallback", "blurDataURL", "aspect", "glowHex", "withinBudget"] as const;

const slim = (entry: Record<string, unknown>): HeroMediaEntry =>
  Object.fromEntries(Object.entries(entry).filter(([key]) => (RUNTIME_KEYS as readonly string[]).includes(key))) as unknown as HeroMediaEntry;

export const HERO_MEDIA: Record<string, HeroMediaEntry> = {
${Object.entries(manifest.entries).map(([key, entry]) => `  ${JSON.stringify(key)}: slim(${JSON.stringify(entry, null, 2)}),`).join("\n")}
};
`;

fs.writeFileSync(path.join(ROOT, "lib", "catalog", "hero-manifest.ts"), ts);

const over = Object.entries(manifest.entries).filter(([, entry]) => !(entry as { withinBudget: boolean }).withinBudget);
for (const [key] of over) {
  failures += 1;
  process.exitCode = 1;
  console.error(`[hero-images] OVER BUDGET: ${key}`);
}
console.log(`[hero-images] manifest written (${Object.keys(manifest.entries).length} entries)`);
if (failures > 0) process.exit(1);
